config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  get "dashboard", to: "pages#dashboard"

  resources :pokemons do
    resources :bookings, only: [:create]
  end

  patch "booking/:id/accepted", to: "bookings#accepted", as: :booking_accepted
  patch "booking/:id/refused", to: "bookings#refused", as: :booking_refused
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :pokemon
  belongs_to :user
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :bookings, dependent: :destroy


  include PgSearch::Model

  pg_search_scope :my_search,
  against: [ :name, :description, :pokemon_type ],
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pokemons, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :bookings_as_owner, through: :pokemons, source: :bookings

  validates :password, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @garage = Pokemon.find(params[:garage_id])
    @booking.pokemon = @pokemon
    @booking.status = "pending"
    authorize @booking
    if @booking.save
      flash[:success] = "Réservation créée avec succès !"
      redirect_to dashboard_path
    else
      render :action => 'new'
    end
  end

  def accepted
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.status = "accepted"
    @booking.save
    redirect_to dashboard_path
  end

  def refused
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.status = "refused"
    @booking.save
    redirect_to dashboard_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def dashboard
    @pokemons = current_user.pokemons
    @bookings = current_user.bookings
    @bookings_as_owner = current_user.bookings_as_owner
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController

  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @pokemons = policy_scope(Pokemon)
    if params[:query].present?
      @pokemons = Pokemon.my_search(params[:query])
    else
      @pokemons = policy_scope(Pokemon)
    end
  end

  def show
    @booking = Booking.new
    @pokemon = Pokemon.find(params[:id])
    authorize @pokemon
  end

  def new
    @pokemon = Pokemon.new
    authorize @pokemon
  end

  def create
    @pokemon = Pokemon.new(pokemon_params)
    @pokemon.user = current_user
    authorize @pokemon
    if @pokemon.save
      redirect_to pokemon_path(@pokemon)
    else
      render :new, status: :unprocessable_entity
    end

  end

  private

  def pokemon_params
    params.require(:pokemon).permit(:name, :description, :photo, :pokemon_type, :price, :level)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RbnbPokemon</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="dash-container">
  <h1>Bienvenue sur ton Dashboard ! Trainer <%= current_user.email %>!</h1>
  <%= link_to "index des pokemon", pokemons_path%>



  <h2>Vos Pokemons</h2>

  <% @pokemons.each do |pokemon| %>
    <br><br><br><br><br>
    <p><%= pokemon.name %></p>
    <%= cl_image_tag pokemon.photo.key, height: 300, width: 400, crop: :fill %>
  <% end %>




  <h2>Demande de reservation</h2>

  <% @bookings_as_owner.each do |booking| %>
    <div>

      <br>
      <p><%= booking.pokemon.titre.upcase %></p>
      <br>
      <p>De : <%= booking.user.email %></p>
      <p>Du : <%= booking.start_date.strftime('%-d %b. %y') %></p>
      <p>Au : <%= booking.end_date.strftime('%-d %b. %y') %></p>
      <br>
      <% if booking.status == "accepted" || booking.status == "refused" %>

          <p class="<%= booking.status == 'accepted' ? 'accepted-confirmation' : ' refused-confirmation' %>">
          <strong><%= booking.status.upcase %></strong></p>
      <% end %>


      <br>
      <p>
        <% if booking.status == "pending"%>
          <!-- <%= link_to "accepted", booking_accepted_path(booking), data: {turbo_method: :patch, turbo_confirm: "Are you sure to accept?"} %> || -->
          <%= link_to "accepter", booking_accepted_path(booking), { class: "accepted-link", data: {turbo_method: :patch, turbo_confirm: "Are you sure to accept?"} } %> ||
          <!-- <%= link_to "refused", booking_refused_path(booking), data: {turbo_method: :patch, turbo_confirm: "Are you sure to decline?"} %> || -->
          <%= link_to "refuser", booking_refused_path(booking), { class: "refused-link", data: {turbo_method: :patch, turbo_confirm: "Are you sure to decline?"} } %>
        <% end %>
      </p>
      <br>
    </div>


  <% end %>



  <h2>Vos Pokemons</h2>

  <% @bookings.each do |booking| %>
    <br><br><br><br><br>
    <p><%= booking.pokemon.name %></p>
    <%= cl_image_tag booking.photo.key, height: 300, width: 400, crop: :fill %>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="home-background">

  <div class="home-titre">
    <h1>Pokemon Choose</h1>
  </div>


  <div class="home-container">

    <div class="home-left">
      <%= image_tag("elec.png")%>

    </div>

    <div class="home-right">
      <p>Bienvenue sur Pokémon Choose ! Vous pouvez louer des Pokémon de différents types et niveaux pour adapter votre stratégie à chaque combat et pour affronter vos adversaires avec un avantage compétitif.
      <br>
      <br>
      Si vous êtes propriétaire d'un Pokémon, vous pouvez le mettre à disposition des autres entraîneurs en fixant le prix et les conditions de location.
      <br>
      <br>
      Rejoignez-nous dès maintenant pour louer les meilleurs Pokémon pour vos combats !</p>
      <%= link_to "Découvrir", pokemons_path, class: "button-74"%>
    </div>

  </div>
</div>

app/views/pokemons/index.html.erb
<div class="body-index">
  <div class="fondu-haut-index">
    <%= render "shared/navbar" %>
  </div>


  <div class="logo">
    <%= image_tag("logo.png") %>
  </div>

  <div class="index-proposition">
    <p><%= link_to "ajouter votre pokemon",  new_pokemon_path, class: "button"%></p>
  </div>



  <!-- debut searchbar (changer le style)-->

  <div class="row justify-content-center">
    <div class="col-sm-8 my-3">
      <%= form_with url: pokemons_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Type a keyword"
          %>
        <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

  <!-- fin searchbar-->



  <div class="grid-index">

    <% if @pokemons.any? %>

      <% @pokemons.each do |pokemon| %>
        <%= link_to pokemon_path(pokemon), class: "link-card" do%>
          <div class="card-container">

            <div class="index-card-jaune">

              <% if pokemon.pokemon_type == "feu" %>
                <div class="index-card-rouge">
              <% elsif pokemon.pokemon_type == "plante"%>
                <div class="index-card-vert">
              <% elsif pokemon.pokemon_type == "normal"%>
                <div class="index-card-normal">
              <% elsif pokemon.pokemon_type == "electrique"%>
                <div class="index-card-eleck">
              <% else %>
                <div class="index-card-blue">
              <% end %>

                  <div class="index-card-nom-level-pv">
                    <p><%= pokemon.name %></p>
                    <p>lvl <%= pokemon.level %></p>
                    <p>80 pv</p>
                  </div>

                  <div class="index-card-photo">
                    <%= cl_image_tag pokemon.photo.key, height: 200, width: 280, crop: :fill %>
                    <!-- width max -->
                  </div>

                  <div class="index-card-description">
                    <p><%= pokemon.description %></p>
                  </div>

                </div>
            </div>
            <div class="index-card-price">
              <p><%= pokemon.price %> pieces</p>
            </div>

          </div>
        <% end %>
      <% end %>

    <% else %>
        <em>Sorry, no movies found.</em>
    <% end %>

  </div>

  <div class="fondu-bas-index"></div>
</div>

app/views/pokemons/new.html.erb
<%= render "shared/navbar" %>
<h1>ajoutez votre pokemon</h1>
<%= simple_form_for @pokemon do |f| %>
  <%= f.input :name, placeholder: 'Nom de votre pokemon' %>
  <%= f.input :description, placeholder: 'description.....' %>
  <%= f.input :price, placeholder: '50€' %>
  <%= f.input :pokemon_type, placeholder: 'type' %>
  <%= f.input :level, placeholder: 'level' %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/pokemons/show.html.erb
<div class="body-show">
  <div class="fondu-haut-index">
    <%= render "shared/navbar" %>
  </div>

  <div class="body-content">
  </div>
  <div class="container-show-glass">
    <div class="show-content">
      <h1>la show de <%= @pokemon.name %></h1>
      <p>lvl.<%= @pokemon.level %></p>


      <%= cl_image_tag @pokemon.photo.key, height: 300, width: 400, crop: :fill %>
      <div class="show-type-price">
        <p><%= @pokemon.pokemon_type %></p>
        <p><%= @pokemon.price %> pieces</p>
      </div>
      <div class="show-description">
        <p><%= @pokemon.description %></p>
      </div>

      <!-- debur form reservation-->

      <%= form_for @booking, url: pokemon_bookings_path(@pokemon), method: :post do |f| %>
        <div class="field">
          <%= f.label :start_date %><br>
          <%= f.datetime_field :start_date, class: "form-control" %>
        </div>

        <div class="field">
          <%= f.label :end_date %><br>
          <%= f.datetime_field :end_date, class: "form-control" %>
        </div>

        <div class="actions">
          <%= f.submit "Réserver", class: "btn btn-primary" %>
        </div>
      <% end %>
      <!-- fin form reservation -->


    </div>
  </div>
    <div class="show-link">
      <p><%= link_to "revoir tout les pokemon", pokemons_path %></p>
      <p><%= link_to "réserver", pokemons_path %></p>
    </div>


  <div class="fondu-bas-show"></div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>